// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pim3semestre.Data;

#nullable disable

namespace pim3semestre.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412013020_unique")]
    partial class unique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.Property<int>("CompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraID"));

                    b.Property<DateTime>("CompraData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompraDataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompraStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FornecedorID")
                        .HasColumnType("int");

                    b.HasKey("CompraID");

                    b.HasIndex("FornecedorID");

                    b.ToTable("ComprasEstoque");
                });

            modelBuilder.Entity("pim3semestre.Models.FornecedorModel", b =>
                {
                    b.Property<int>("FornecedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FornecedorID"));

                    b.Property<bool>("FornecedorAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("FornecedorBairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FornecedorCEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FornecedorCNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("FornecedorCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FornecedorEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FornecedorEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FornecedorLogradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FornecedorNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FornecedorNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FornecedorTelefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("FornecedorID");

                    b.HasIndex("FornecedorCNPJ")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemCompraModel", b =>
                {
                    b.Property<int>("ItemCompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCompraID"));

                    b.Property<int>("CompraID")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCompraPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemCompraQtd")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("ItemCompraID");

                    b.HasIndex("CompraID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ItensCompra");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemVendaModel", b =>
                {
                    b.Property<int>("ItemVendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemVendaID"));

                    b.Property<decimal>("ItemVendaCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItemVendaPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemVendaQtd")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemVendaTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("pim3semestre.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.Property<int>("MovimentacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimentacaoID"));

                    b.Property<int?>("ItemCompraID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemVendaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovimentacaoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovimentacaoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovimentacaoQtd")
                        .HasColumnType("int");

                    b.Property<string>("MovimentacaoTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("MovimentacaoID");

                    b.HasIndex("ItemCompraID");

                    b.HasIndex("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("pim3semestre.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoID"));

                    b.Property<bool>("ProdutoAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("ProdutoCodBarra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProdutoDescricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProdutoEstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProdutoPrecoCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProdutoPrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProdutoPromocao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProdutoQtdEstoque")
                        .HasColumnType("int");

                    b.HasKey("ProdutoID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("pim3semestre.Models.VendaFinalModel", b =>
                {
                    b.Property<int>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaID"));

                    b.Property<DateTime>("VendaData")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendaTipoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VendaValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaID");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.HasOne("pim3semestre.Models.FornecedorModel", "Fornecedor")
                        .WithMany("Compras")
                        .HasForeignKey("FornecedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemCompraModel", b =>
                {
                    b.HasOne("pim3semestre.Models.CompraEstoqueModel", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CompraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemVendaModel", b =>
                {
                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pim3semestre.Models.VendaFinalModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("pim3semestre.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.HasOne("pim3semestre.Models.ItemCompraModel", "ItemCompra")
                        .WithMany()
                        .HasForeignKey("ItemCompraID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pim3semestre.Models.ItemVendaModel", "ItemVenda")
                        .WithMany()
                        .HasForeignKey("ItemVendaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCompra");

                    b.Navigation("ItemVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("pim3semestre.Models.FornecedorModel", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("pim3semestre.Models.VendaFinalModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
