// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pim3semestre.Data;

#nullable disable

namespace pim3semestre.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pim3semestre.Models.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("CategoriaDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriaNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("pim3semestre.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("ClienteCPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClienteDataNas")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.Property<int>("CompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraID"));

                    b.Property<DateTime>("CompraData")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CompraValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FornecedorID")
                        .HasColumnType("int");

                    b.HasKey("CompraID");

                    b.HasIndex("FornecedorID");

                    b.ToTable("ComprasEstoque");
                });

            modelBuilder.Entity("pim3semestre.Models.FornecedorModel", b =>
                {
                    b.Property<int>("FornecedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FornecedorID"));

                    b.Property<string>("FornecedorBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorCNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorLogradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FornecedorID");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("pim3semestre.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("FuncionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioID"));

                    b.Property<string>("FuncionarioCPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FuncionarioDataNas")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuncionarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuncionarioID");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemCompraModel", b =>
                {
                    b.Property<int>("ItemCompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCompraID"));

                    b.Property<int>("CompraID")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCompraPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemCompraQtd")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("ItemCompraID");

                    b.HasIndex("CompraID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ItensCompra");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemVendaModel", b =>
                {
                    b.Property<int>("ItemVendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemVendaID"));

                    b.Property<decimal>("ItemVendaPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemVendaQtd")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("pim3semestre.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.Property<int>("MovimentacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimentacaoID"));

                    b.Property<int?>("ItemCompraID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemVendaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovimentacaoData")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovimentacaoQtd")
                        .HasColumnType("int");

                    b.Property<string>("MovimentacaoTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("MovimentacaoID");

                    b.HasIndex("ItemCompraID");

                    b.HasIndex("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("pim3semestre.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<bool>("ProdutoAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("ProdutoCodBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdutoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdutoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProdutoPrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoQtdEstoque")
                        .HasColumnType("int");

                    b.HasKey("ProdutoID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("pim3semestre.Models.VendaFinalModel", b =>
                {
                    b.Property<int>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaID"));

                    b.Property<int?>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VendaData")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendaTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VendaValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("FuncionarioID");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.HasOne("pim3semestre.Models.FornecedorModel", "Fornecedor")
                        .WithMany("Compras")
                        .HasForeignKey("FornecedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemCompraModel", b =>
                {
                    b.HasOne("pim3semestre.Models.CompraEstoqueModel", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CompraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("pim3semestre.Models.ItemVendaModel", b =>
                {
                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pim3semestre.Models.VendaFinalModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("pim3semestre.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.HasOne("pim3semestre.Models.ItemCompraModel", "ItemCompra")
                        .WithMany()
                        .HasForeignKey("ItemCompraID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pim3semestre.Models.ItemVendaModel", "ItemVenda")
                        .WithMany()
                        .HasForeignKey("ItemVendaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pim3semestre.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCompra");

                    b.Navigation("ItemVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("pim3semestre.Models.ProdutoModel", b =>
                {
                    b.HasOne("pim3semestre.Models.CategoriaModel", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("pim3semestre.Models.VendaFinalModel", b =>
                {
                    b.HasOne("pim3semestre.Models.ClienteModel", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pim3semestre.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Vendas")
                        .HasForeignKey("FuncionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("pim3semestre.Models.CategoriaModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("pim3semestre.Models.ClienteModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("pim3semestre.Models.CompraEstoqueModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("pim3semestre.Models.FornecedorModel", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("pim3semestre.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("pim3semestre.Models.VendaFinalModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
